version: '3'

services:

  portainer:
    image: portainer/agent:lts
    restart: unless-stopped
    container_name: portainer_agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    ports:
      - '9001:9001'